"""
Small, pure helper functions shared across the app.
Kept dependency-free (no Streamlit, no Firebase) so they are trivially
unit-testable.
"""

import uuid
from datetime import datetime, timezone

from utils.constants import TIMESTAMP_DISPLAY_FORMAT


def get_current_utc_datetime() -> datetime:
    """Single source of truth for 'now' so created/updated timestamps are
    always generated by the server, never trusted from user input."""
    return datetime.now(timezone.utc)


def format_timestamp(dt: datetime) -> str:
    """Render a datetime for display, e.g. '09 Sep 2026, 10:30 PM'."""
    if dt is None:
        return "—"
    return dt.strftime(TIMESTAMP_DISPLAY_FORMAT)


def generate_complaint_id() -> str:
    """
    Fallback human-friendly unique ID, used only if the app is run without
    a live Firestore connection (e.g. local/demo mode where Firestore's own
    auto-generated document ID isn't available).

    NOTE: When Firestore is connected, the Firestore document ID is the
    canonical immutable identifier — this function is not used for that
    path. See services/firebase_service.py.
    """
    return f"CMP-{uuid.uuid4().hex[:8].upper()}"


def normalize(value: str) -> str:
    """Trim + collapse case for reliable, non-substring comparisons
    (used by filters and search — see MEDIUM BUG 2 prevention)."""
    if value is None:
        return ""
    return value.strip()


def normalize_for_search(value: str) -> str:
    """Case-insensitive normalization, used only for the free-text
    search box (ID / room number), never for category or status
    comparisons."""
    return normalize(value).lower()
